Vagrant.configure("2") do |config|
  config.vm.box = "rafacas/centos65-i386-plain"
  
  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.provision :ansible do |ansible|
   ansible.playbook = "playbook.yml"
  end

  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
  	v.cpus = 2
  end
end

