Vagrant.configure("2") do |config|
  config.vm.box = "rafacas/centos65-i386-plain"
  
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.provision :ansible do |ansible|
   ansible.playbook = "playbook.yml"
  end

end

