- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart php-fpm
  service: name=php-fpm state=restarted enabled=yes

- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes
